created FirstBallIntoTheShooter and VerticalConveyorTimedCommand
GirlsOfSteelRobotics/GirlsOfSteelFRC pull request #102
Opened 2022-02-16 01:30 UTC by JosephJackson

Justine and Ariella's new FirstBallIntoTheShooter auto command and supporting command

2022-02-17 22:41 UTC, pjreiniger requested changes
Functionally this all makes sense and looks good. Just a little bit of cleanup requested.

2022-02-17 22:41 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/FirstBallIntoTheShooter.java
> +        super(new DriveDistanceCommand(chassis, .762, 0.05),
I'm a dumb american, can you do this in inches and do `Units.inchesToMeters()` . The number should probably be a constant as well, probably OK jsut to have in this class

2022-02-17 22:41 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/FirstBallIntoTheShooter.java
> +            new ShooterRpmPIDCommand(shooter, 2500),
Make a constant, either in `ShooterSubystem` or `Constants`

2022-02-17 22:41 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/FirstBallIntoTheShooter.java
> +            new VerticalConveyorTimedCommand(verticalConveyor, 10));
Make a constant, either in `VerticalConveyorSubsystem` or `Constants`

2022-02-17 22:41 UTC, ashley-wei commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/auto_modes/FirstBallIntoTheShooter.java
> +public class FirstBallIntoTheShooter extends SequentialCommandGroup {
change name of class --> not putting it into the shooter (into the hub) & doesn't specify auto. also helpful to specify that this is the ball in the cargo or just call it something like 'one ball auto'

2022-02-17 22:44 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/commands/VerticalConveyorTimedCommand.java
> +public class VerticalConveyorTimedCommand extends CommandBase {
[Last year ](https://github.com/GirlsOfSteelRobotics/GirlsOfSteelFRC/blob/main/y2020/2020InfiniteRecharge/src/main/java/com/gos/infinite_recharge/auto_modes/ShootAndDriveToTrench.java#L52) we used [decoraters](https://docs.wpilib.org/en/stable/docs/software/commandbased/convenience-features.html?highlight=withtimeout) for stuff like timeouts

2022-02-18 00:47 UTC, pjreiniger approved these changes

2022-02-18 00:55 UTC, merged