Taxi autonomous
GirlsOfSteelRobotics/GirlsOfSteelFRC pull request #81
Opened 2022-01-29 17:57 UTC by squdgy7

completed command to drive a certain distance off the tarmac

2022-02-01 00:12 UTC, pjreiniger approved these changes

2022-02-01 00:12 UTC, pjreiniger commented on codelabs/first_robot_code/src/main/java/com/gos/codelabs/first_code_lab/Robot.java
>          boolean trigger = m_stick.getTrigger(); // NOPMD
Doesn't seem like this should be part of this PR

2022-02-01 00:12 UTC, pjreiniger commented on codelabs/gitflow/src/main/java/com/gos/codelabs/gitflow/RobotContainer.java
>  import com.gos.codelabs.gitflow.subsystems.PJCodelab2021Part1Subsystem;
Doesn't seem like this should be part of this PR

2022-02-01 00:12 UTC, pjreiniger commented on codelabs/gitflow/src/main/java/com/gos/codelabs/gitflow/RobotContainer.java
> +    private KellyCodelab2021Part1Subsystem m_kellyCodeLab2021Part1;
Doesn't seem like this should be part of this PR

2022-02-01 00:12 UTC, pjreiniger commented
Don't worry if bazel fails the CI checks.

2022-02-01 00:13 UTC, pjreiniger requested changes
Changed my mind. Requesting changes

2022-02-01 00:25 UTC, ashley-wei reviewed
you did great!!! :)

2022-02-03 23:23 UTC, pjreiniger approved these changes

2022-02-09 01:01 UTC, merged