Grace shooter/conveyor
GirlsOfSteelRobotics/GirlsOfSteelFRC pull request #89
Opened 2022-02-05 20:08 UTC by ashley-wei

2022-02-05 20:58 UTC, pjreiniger requested changes

2022-02-05 20:58 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/Constants.java
> +    // not can
While true, I think saying `// PWM` would be better. Maybe throw a comment before the previous defs that says `// CAN`

2022-02-05 20:58 UTC, pjreiniger commented on libraries/GirlsOfSteelLib/src/main/java/com/gos/lib/properties/PropertyManager.java
> +        public TypeT getValue() {
idk how / why this got reverted, but it is important for PMD

2022-02-05 20:58 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/commands/ShooterPIDCommand.java
> +public class ShooterPIDCommand extends CommandBase {
Nit: PID in this situation can be seen as ambiguous. What are you PID'ing? I might change it to have `RPM` in the name.

2022-02-05 20:58 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/commands/ShooterPIDCommand.java
> +        m_shooter.setShooterPIDSpeed(m_goalRPM);
Similar thing here with the function name

2022-02-05 20:58 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/commands/tuning/TuneShooterGoalRPMCommand.java
> +    private static final PropertyManager.IProperty<Double> SHOOTER_GOAL = new PropertyManager.DoubleProperty("Shooter Goal", 0);
Nit: Constants at the top, then member variables

Nit: I would probably put "RPM" somewhere in the display name (`"Shooter Goal"`). Maybe "Tune" in there somewhere as well.

2022-02-05 20:58 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/commands/tuning/TuneShooterGoalRPMCommand.java
> +
The tuning one should definitely stop the motor on `end`

2022-02-05 20:58 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/commands/tuning/TuneShooterMotorSpeedCommand.java
> +    public static final PropertyManager.IProperty<Double> SHOOTER_SPEED = new PropertyManager.DoubleProperty("Motor Speed", 0);
At the very least include "Shooter" in the display name (`"Motor Speed"`)

2022-02-05 20:58 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/subsystems/ShooterSubsystem.java
> +            .addMaxVelocity(0)
max accel and max velocity are used for Trapezoidal Motion Profiles (aka SmartMotion, MotionMagic). Not necessary for velocity controllers

2022-02-05 20:58 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/subsystems/ShooterSubsystem.java
> +            FlywheelSim flywheelSim = new FlywheelSim(DCMotor.getNeo550(2), 1.66, .008);
Grace gave us an updated gear ration of 1:1 since they originally wrote this. We might be able to ask them the moment of inertia, but keeping the `.008` probably won't hurt our simulation that much if we just keep it from last year

2022-02-05 20:58 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/subsystems/ShooterSubsystem.java
> +    public double getEncoder() {
Get encoder what? Distance or velocity? It seems like we should be returning RPM here (`m_encoder.getVelocity()`, see line 62) instead of position

2022-02-05 20:58 UTC, pjreiniger commented on y2022/RapidReact/src/main/java/com/gos/rapidreact/commands/ShooterPIDCommand.java
> +        double error = Math.abs(m_goalRPM - m_shooter.getEncoder());
See comment in the subsystem. `getEncoder` seems to return position, so this logic is using different units

2022-02-05 21:00 UTC, pjreiniger commented
Also update the title. This is only for the shooter, and the name probably shouldn't be part of it.

Also, pro-tip, if you put `closes #64` in the description of the PR (click the three dots and select edit), the issue will automatically get linked and closed when this lands

2022-02-07 23:01 UTC, ashley-wei commented
closes #64

2022-02-07 23:37 UTC, pjreiniger approved these changes

2022-02-07 23:42 UTC, merged